

package io.ktor.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.ktor.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/openapi")
@TestDataPath("$PROJECT_ROOT")
public class OpenapiTestGenerated extends AbstractOpenapiTest {
  @Test
  public void testAllFilesPresentInOpenapi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/openapi"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("Authentication.kt")
  public void testAuthentication() {
    runTest("compiler-plugin/testData/openapi/Authentication.kt");
  }

  @Test
  @TestMetadata("Functions.kt")
  public void testFunctions() {
    runTest("compiler-plugin/testData/openapi/Functions.kt");
  }

  @Test
  @TestMetadata("Nesting.kt")
  public void testNesting() {
    runTest("compiler-plugin/testData/openapi/Nesting.kt");
  }

  @Test
  @TestMetadata("Templates.kt")
  public void testTemplates() {
    runTest("compiler-plugin/testData/openapi/Templates.kt");
  }

  @Test
  @TestMetadata("TypeParameters.kt")
  public void testTypeParameters() {
    runTest("compiler-plugin/testData/openapi/TypeParameters.kt");
  }
}
