

package io.ktor.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.ktor.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/openapi")
@TestDataPath("$PROJECT_ROOT")
public class OpenapiTestGenerated extends AbstractOpenapiTest {
  @Test
  public void testAllFilesPresentInOpenapi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/openapi"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("Extracted.kt")
  public void testExtracted() {
    runTest("compiler-plugin/testData/openapi/Extracted.kt");
  }

  @Test
  @TestMetadata("SimpleNested.kt")
  public void testSimpleNested() {
    runTest("compiler-plugin/testData/openapi/SimpleNested.kt");
  }
}
